// v:10.6.16
var skimlinks_pub_id = '19167X763888';
var skimlinks_site = 'audi-sport.net';
var skimwords_hover_name = 'dark';
var skimwords_horizontal_distance = 35;
var skimwords_vertical_distance = 35;
var noskoupon = true;
var noskimproducts = true;
var skimwords_instant = true;
(function(){var Za,xc,yc;function Kd(){y=g.document;H={jQueryUrl:"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js",jQueryMinVersion:"1.4.4",jQueryMaxVersion:"1.7.9",pixelPath:"//t.skimresources.com/",sw_domain:g.skimlinks_domain||"go.redirectingat.com",instantApiUrl:"//i.skimresources.com/api/",sw_domain:g.skimlinks_domain||"go.redirectingat.com",skimwordsApiUrl:"//i.skimresources.com/api/",skimwordsLiteUrl:"//s.skimresources.com/js/lite/",productCSSDomain:"//s.skimresources.com/css/flyover-",
trackingApiUrl:"//t.skimresources.com/api/",delayBeforeFadeOut:250};$a=y.createTextNode("").nodeName;zc=function(){};Fb=Gb=null;Na=0;E=null;Hb="<div id='flyover2-{{id}}' class='flyover2-outer {{multiclass}}'><div class='flyover2-body'></div><div class='flyover2-bottom'><a class='bottom-link' target='_blank' href='http://www.skimlinks.com/?ref=flyover' ref='hoverover'></a><a class='bottom-link-2' title='{{hover_title}}'></a></div></div>";Na=0;T=!1;ab=null;Y="";bb=Oa="02";cb="en";Ib=Ac=0;db=eb=!1;Jb=
'<div class="flyover2-row">{{closeButton}}{{imageLink}}{{titleLink}}<div class="flyover2-box-container"><div class="flyover2-merc-section"><span class="flyover2-merc">{{merchantLink}}</span></div><div class="flyover2-price">{{priceLink}}</div>{{emptyLink}}<br /></div></div>';Kb='<div class="flyover2-row {{extraClass}}"><div class="flyover2-merc-section"><span class="flyover2-merc">{{merchantLink}}</span></div><div class="flyover2-price">{{priceLink}}</div>{{emptyLink}}<br /></div>';Lb='<div class="flyover2-row first"><div class="flyover2-close nowidth"></div>{{imageLink}}{{titleLink}}</div>';
Mb='<div class="flyover2-row"><div class="flyover2-search-section">{{link1}}</div>{{link2}}</div>';Nb=73;Ob=55;fb=!1}function Bc(b){var c=b.indexOf(" "),d=b;-1!==c&&(d=b.substring(0,c));return d}function Cc(b){b=b.relatedNode;if(Ca||g.stop_skimwords_ajax)return!1;Pb&&clearTimeout(Pb);Qb++;1==Qb&&L.reset();L.traverse_node(b);L.get_non_colliding_nodes()&&1<=Rb&&(Pb=setTimeout(function(){Qb=0;Dc({})},500))}function Ec(b,c){1E7<b&&6!==c&&(b-=1E7);return b}function Ld(){F=ma;C=function(){var b=/^\s+/,
c=/\s+$/;/\S/.test("\u00a0")&&(b=/^[\s\xA0]+/,c=/[\s\xA0]+$/);return{trim:String.prototype.trim?function(b){return null==b?"":String.prototype.trim.call(b)}:function(d){return null==d?"":d.toString().replace(b,"").replace(c,"")},inArray:function(b,c,f){var h;if(c){if(Array.prototype.indexOf)return Array.prototype.indexOf.call(c,b,f);h=c.length;for(f=f?0>f?Math.max(0,h+f):f:0;f<h;f++)if(f in c&&c[f]===b)return f}return-1},support:function(){var b,c,f,h=y.body;c=!0;b=y.createElement("div");b.style.cssText=
"visibility:hidden;border:0;width:0;height:0;position:static;top:0;margin-top:1px";h.insertBefore(b,h.firstChild);c=y.createElement("div");b.appendChild(c);c.innerHTML="<table><tr><td style='padding:0;border:0;display:none'></td><td>t</td></tr></table>";f=c.getElementsByTagName("td");f[0].style.display="";f[1].style.display="none";c.innerHTML="";c.style.width=c.style.paddingLeft="1px";c=2===c.offsetWidth;h.removeChild(b);return{boxModel:c}}(),create:F,add_class:function(b,c){class_re=RegExp("\\b"+
na(c)+"\\b");class_re.test(b.className)||(b.className+=" "+c)},remove_class:function(b,c){class_re=RegExp("\\b"+na(c)+"\\b","g");if(class_re.test(b.className))b.className=b.className.replace(class_re,"")},set_html:function(b,c){b.innerHTML=c},size:function(b){var c,f=0;for(c in b)b.hasOwnProperty(c)&&f++;return f}}}()}function Sb(){Kd();Da=g.skimwords_standard||!1;Ea=g.skimwords_lite||!1;ea=g.force_location||M.href;gb=g.skimwords_hover_name||"dark";fa=null==g.skimwords_instant?!0:g.skimwords_instant;
Fc=g.skimwords_horizontal_distance||0;Gc=g.skimwords_vertical_distance||0;Tb=g.skimwords_block_ie7||!1;Hc=g.skimwords_no_limit||!1;Ic=g.skimwords_link_all||!1;sw_debug=g.skimwords_debug||0;Ub=g.skimwords_force_country||!1;Jc=g.skimwords_force_domain_check||!1;Vb=g.skimwords_force_tree||!1;Wb=g.skimwords_prio_threshold||0;hb=g.skimwords_diy||!1;Xb=g.skimwords_diy_filter||!1;Yb=g.skimwords_whitelist_filter||!1;J=g.skimlinks_pub_id||"";Zb=g.skimlinks_maxproducts||3;ib=g.noskimproducts||!1;__noevents=
g.noevents||!1;Kc=g.nounlinked||!1;Lc=g.skimwords_no_visual||!1;db=g.skimwords_merchant_excludes||!1;eb=g.skimwords_merchant_includes||!1;ga=window.skimwords_branded_merchant||!1;var b=ea,c="sessid,aspsessionid,aspsession-id,cftoken,j-sessionid,jsessid,jsessionid,jsession_id,phpsessid,phpsession-id,phpsessionid,seskey,session-id,session-key,sessionid,sessionkey,session_id,uniqueid,utm_source,utm_medium,utm_campaign,utm_term".split(","),d;for(d=0;d<c.length;d++){var e=c[d],f=void 0,h=void 0,j=void 0,
k=j=f=void 0,f=b.split("?");if(2<=f.length){h=f.shift();j=f.join("?");f=encodeURIComponent(e)+"=";j=j.split(/[&;]/gi);for(k=j.length;0<k--;)-1!==j[k].lastIndexOf(f,0)&&j.splice(k,1);b=h+"?"+j.join("&")}}"?"==b[b.length-1]&&(b=b.substr(0,b.length-1));ea=b;ga&&(ga=parseInt(ga));$b=window.skimwords_branded_merchant_url||!1;g.skimwords_flyover_version&&(bb=g.skimwords_flyover_version);if(g.skimwords_instant_api_location)H.instantApiUrl=g.skimwords_instant_api_location,H.skimwordsApiUrl=g.skimwords_instant_api_location;
if(g.skimwords_css_location)H.productCSSDomain=g.skimwords_css_location;if(Ea||Da)fa=!0;g.skimwords_flyover_template&&(Hb=g.skimwords_flyover_template);g.skimwords_flyover_loop_multi&&(Jb=g.skimwords_flyover_loop_multi);g.skimwords_flyover_loop_simple&&(Kb=g.skimwords_flyover_loop_simple);g.skimwords_flyover_before&&(Lb=g.skimwords_flyover_before);g.skimwords_flyover_after&&(Mb=g.skimwords_flyover_after);g.skimwords_flyover_max_title_multi&&(Nb=g.skimwords_flyover_max_title_multi);g.skimwords_flyover_max_title_single&&
(Ob=g.skimwords_flyover_max_title_single);Y=Da?Y+"1":Ea?Y+"2":Y+"3";ib&&(bb=Oa="00");gb&&(Y+=gb);Tb&&(Y+="ie7block");D.pag=ea;Mc&&Mc()}function ac(b){G(b,"click",U);G(b,"contextmenu",U)}function Md(b){var c=y.createElement("div");c.innerHTML=b;c=c.childNodes[0];y.body.appendChild(c);return c}function Nd(b,c,d){var e,f;f=[];E=Md(b);G(E,"mouseover",function(){T=!0});G(E,"mouseout",function(){jb();T=!1});var h=d?"branded-":"flyover2-",b=K(E,h+"body")?E:ha(E,h+"body")[0];C.set_html(b,c);e=ha(b,"skimwords-hover-link");
for(c=0,d=e.length;c<d;c++)f.push(e[c]);e=ha(b,"skimwords-ebay-link");for(c=0,d=e.length;c<d;c++)f.push(e[c]);for(c=0,d=f.length;c<d;c++)e=f[c],ac(e);f=ha(E,h+"close")[0];G(f,"click",function(){jb();T=!1});f=ha(b,h+"row");for(c=1,d=f.length;c<d;c++)e=f[c],F(e).hover(function(){C.add_class(this,h+"row-hover")},function(){C.remove_class(this,h+"row-hover")});f=ha(b,h+"box-container");for(c=0,d=f.length;c<d;c++)e=f[c],F(e).hover(function(){C.add_class(this,h+"box-container-hover")},function(){C.remove_class(this,
h+"box-container-hover")});return E}function jb(){if(g.skimwords_persistent_flyover)return!1;setTimeout(function(){if(!T&&E){var b=Nc;Fb=(new Date).getTime();var c={};c.dur=Fb-Gb;c.pub=J;c.pag=ea;c.guid=N;c.gid=v(b,"data-group-id");c.phr=bc(b);c.url=v(b,"href");c.ver=v(b,"data-flyover-version");c.pref=R;if(E)c.pc=ha(E,"merc-link").length;b=H.trackingApiUrl+"hover.php?data="+encodeURIComponent(A(c))+(0!=B?"&dnt="+B:"")+(O?"&fdnt=1":"");V(b,!1,{async:!0});Ca=!1;F(E).fadeOut("fast").slideUp();F(E).remove();
T=E=!1}},H.delayBeforeFadeOut)}function Od(b,c,d,e,f,h){v(b,"data-flyover",Na);F(b).unbind("mouseenter");F(b).bind("mouseenter",function(j){ab=setTimeout(function(){var k=c;Ca=!0;var m=Pa(Hb,{id:d,multiclass:e?"flyovermulti":"",hover_title:f?f:""});if(!ia){h&&(m=m.replace(/flyover2/g,"branded"),k=k.replace(/flyover2/g,"branded"),$b&&(k=k.replace('<div class="branded-close nowidth"></div>','<a class="branded-logo skimwords-hover-link" target="_blank" href="'+$b+'"></a><div class="branded-close nowidth"></div>')));
E||Nd(m,k,h);var k=j.pageX,m=j.pageY,g=F(E).width(),n=F(E).height();F(y).width();var p=k,n=0-n-5,p=k-g/2;F(E).css({top:m+"px",left:p+"px",marginTop:n+"px",marginLeft:"0px"});T||F(E).fadeIn("fast")}Gb=(new Date).getTime();Nc=b;T=!0},500)});F(b).unbind("mouseleave");F(b).bind("mouseleave",function(){ab&&clearTimeout(ab);jb();T=!1});Na++}function Pd(b,c){var d,e,f,h,j,k,m,g=[],n=!0;c.sort(function(b,c){return c.group_priority()-b.group_priority()});j=c[0];e=b.multi()?c.length:1;for(d=0;d<e;d++){f=c[d];
k=f.products();for(f=0,h=k.length;f<h;f++){m=Qd(k[f],j);if(g.length===Zb){d=e;break}m.price()&&" "!==m.price()&&(g.push(m),n&&(m.set_first(),n=!1))}}return[j,g]}function Rd(b,c){var d="_sacat=See-All-Categories&_nkw="+c,e="&skimlinks_search_product=ebay&skimlinksurl="+encodeURIComponent("http://www.ebay.com/sch/i.html?")+"&skimlinkspubid="+J,f="http://www.ebay.com/sch/i.html?"+d,d="http://go.redirectingat.com/forms.php?"+d+e;return Pa(Mb,{link1:'<a href="'+f+'" data-skimlinks-href="'+d+'" target="_blank" class="search-link flyover2-clickable skimwords-ebay-link" title="Search on eBay">Search on eBay</a>',
link2:'<a href="'+f+'" data-skimlinks-href="'+d+'" target="_blank" class="flyover2-arrow flyover2-clickable skimwords-ebay-link" title="Search on eBay"></a>'})}function Qa(b,c,d,e,f,h,j,k){var m=10>c.phrase().action_type()?"0"+c.phrase().action_type():c.phrase().action_type(),c="3"+c.flyover_version()+h+m,f=f||"",k=k||b.id(),j=null!=j?j:b.title();return'<a href="'+b.url()+'" class="'+f+' skimwords-link skimwords-hover-link" data-skim-creative="'+c+'" data-skim-product="'+k+'" data-skimwords-word="'+
e+'" data-skimwords-id="'+b.id()+"X"+b.merchant_id()+'" title="'+j+'" target="_blank" border=0>'+d+"</a>"}function Oc(b,c,d){var e,f,h,j=c.is_multi()?Nb:Ob,k=b.title(),m={},g="";f=k;e=b.price();e=e.split(".");e[0]=e[0].split("").reverse().join("");e[0]=e[0].replace(/(\d{3})(?!,)/g,"$1,");e[0]=e[0].split("").reverse().join("");e[0]=0==e[0].indexOf(",")?e[0].substring(1):e[0];price=e.join(".");e=b.image();h=c.currency();c.hover_title();f.length>j&&(f=f.substr(0,j-3)+"...");m.imageLink=Qa(b,c,'<img src="'+
e+'" style="border:0px !important;" title="'+k+'" />',d,"image","1","",b.adjusted_id());m.titleLink=Qa(b,c,f,d,"product-link flyover2-link","2",k,b.adjusted_id());m.merchantLink=Qa(b,c,b.merchant_name(),d,"merc-link flyover2-clickable","3","");m.priceLink=Qa(b,c,h+price,d,"flyover2-clickable","3","");m.emptyLink=Qa(b,c,"",d,"flyover2-arrow product-link","2",k);m.plainLink=b.url();c.is_multi()?(m.closeButton=b.is_first()?"<div class='flyover2-close nowidth'></div>":"",g=Pa(Jb,m)):(b.is_first()?(g=
Pa(Lb,m),m.extraClass="flyover2-row-main"):m.extraClass="",g+=Pa(Kb,m));return g}function Sd(b){function c(b){for(var c=[],d=256,e={},f=0;256>f;f++)e[String.fromCharCode(f)]=f;for(var h="",f=0,j=b.length;f<j;f++){var k=b.charAt(f),m=h+k;e[m]?h=m:(c.push(e[h]),e[m]=d++,h=""+k)}""!=h&&c.push(e[h]);return c}function d(b){for(var c=256,d=[],e=8,f=0,h=0,k=0,j=b.length;k<j;k++){f=(f<<e)+b[k];h+=e;c++;for(c>>e&&e++;7<h;)h-=8,d.push(f>>h),f&=(1<<h)-1}d.push(h?f<<8-h:"");return d}function e(b){for(var c=[],
d=0,e=0,f="",h=0,k=b.length;h<k;h++){var j=b[h];127<j&&(j-=128,e+=Math.pow(2,d));0==j||34==j||37==j||38==j||39==j||43==j||61==j||92==j?c.push("="+String.fromCharCode(j+16)):c.push(String.fromCharCode(j));d++;6<d&&(f+=0==e||34==e||37==e||38==e||39==e||43==e||61==e||92==e?"="+String.fromCharCode(e+16)+c.join(""):String.fromCharCode(e)+c.join(""),c=[],d=e=0)}return f+=0==e||34==e||37==e||38==e||39==e||43==e||61==e||92==e?"="+String.fromCharCode(e+16)+c.join(""):String.fromCharCode(e)+c.join("")}for(var b=
String.fromCharCode(74)+b,f="",h=0,j=0,k=0;256>k;k++)f+=String.fromCharCode(224);for(var m=256,g={},k=0;256>k;k++)g[String.fromCharCode(k)]=k;for(var n=[],p="",l="",k=0,q=b.length;k<q;k++){var t=b.charAt(k),r=t.charCodeAt(0);if(255<r){var z=r;switch(r){case 8364:r=128;break;case 8218:r=130;break;case 402:r=131;break;case 8222:r=132;break;case 8230:r=133;break;case 8224:r=134;break;case 8225:r=135;break;case 710:r=136;break;case 8240:r=137;break;case 352:r=138;break;case 8249:r=139;break;case 338:r=
140;break;case 381:r=142;break;case 8216:r=145;break;case 8217:r=146;break;case 8220:r=147;break;case 8221:r=148;break;case 8226:r=149;break;case 8211:r=150;break;case 8212:r=151;break;case 732:r=152;break;case 8482:r=153;break;case 353:r=154;break;case 8250:r=155;break;case 339:r=156;break;case 382:r=158;break;case 376:r=159}z!=r?(t=String.fromCharCode(r),j++,h++,256<=h&&(p+=f,h=0)):(0<h&&(p+=f.substr(0,h),h=0),p+=String.fromCharCode(parseInt(r/256)))}else j++,h++,256<=h&&(p+=f,h=0);z=l+t;g[z]?l=
z:(255<r&&(t=String.fromCharCode(r%256)),n.push(g[l]),g[z]=m++,l=""+t)}""!=l&&n.push(g[l]);0<h&&(p+=f.substr(0,h));f=e(d(n));return b.length!=j?(b=e(d(c(p))),f+"=="+b):f}function Dc(b){var c=b.compress||0,d="",e,f,h="",j,k,m,b=H.instantApiUrl;Ca=!0;d=L.get_non_colliding_nodes();j={};for(f in d)if(d.hasOwnProperty(f)&&(k=d[f],m=k.nodeName===$a?C.trim(k.nodeValue):null)){if(k.parentNode){try{e=k.parentNode.getBoundingClientRect()}catch(s){e={left:0,top:0,width:100,height:100}}k={Contents:m,X:e.left,
Y:e.top,W:e.width,H:e.height}}else k={Contents:m,X:0,Y:0,W:100,H:100};j[f]=k}d=A(j);c&&(c=1,d=Sd(d));Da?h="standard":Ea?h="lite":Xb?h="diy":Yb&&(h="whitelist");if("msie"===w.browser&&!g.XDomainRequest)fa=!1,Fa("skimwordsDataCallback");else{e={data:'{"instant":"1","pubcode":"'+J+'","page":"'+ea+'","pref":"'+R+'"'+(Ub?',"force_country":"'+Ub+'"':"")+(Vb?',"force_tree":"'+Vb+'"':"")+(db?',"merchant_excludes":"'+db+'"':"")+(eb?',"merchant_includes":"'+eb+'"':"")+(hb?',"diy":"1"':"")+"}",content:d,dnt:B,
fdnt:O?"1":"",version:"10",js:1};Jc&&(e.force_domain_check=1);c&&(e.compressed=1);sw_debug&&(e.debug=sw_debug);h&&(e.filter=h);c=[];for(f in e)e.hasOwnProperty(f)&&c.push(""+f+"="+x(e[f]));f=c.join("&");if("msie"!==w.browser){var n=!1,p;p=new XMLHttpRequest;p.open("POST",b,!0);p.setRequestHeader("Content-type","application/x-www-form-urlencoded");"withCredentials"in p&&(p.withCredentials=!0);p.async="true";p.onreadystatechange=function(){if(!n&&4===p.readyState)if(n=!0,200===p.status){var b={},b=
JSON&&JSON.parse?JSON.parse(p.responseText):eval("("+p.responseText+")");kb(b)}else fa=!1,Fa("skimwordsDataCallback")};try{p.send(f)}catch(l){}}else if(g.XDomainRequest){var q=new XDomainRequest;"withCredentials"in q&&(q.withCredentials=!0);if(q){q.open("POST",b,!0);q.onload=function(){var b={};try{b=JSON.parse(q.responseText)}catch(c){b=eval("("+q.responseText+")")}kb(b)};q.onerror=function(){};q.onprogress=function(){};q.ontimeout=function(){};q.async=!0;try{q.send(f)}catch(t){fa=!1,Fa("skimwordsDataCallback")}}}else fa=
!1,Fa("skimwordsDataCallback")}}function Pc(b){var c=b.offsetWidth,b=b.offsetHeight;return 468==c&&60==b||234==c&&60==b||728==c&&90==b||300==c&&250==b||250==c&&250==b||336==c&&280==b||160==c&&600==b||120==c&&600==b?!0:!1}function Qc(b){if(b&&-1!==b.indexOf("class=")){if(b=b.match(/([^\[]+)\[class=([^\]]+)\]/i),3==b.length)return b[1]+"."+b[2]}else return b}function Rc(b,c,d,e,f,h,j){b.text().split(" ");var k=na(b.text()),j=j||"skimwords-link";"de"==cc.toLowerCase()&&b.set_title("Shopping link hinzugef\u00fcgt von SkimWords");
"cn"===c||"ko"===c||"ja"===c?(c="(?:"+k+")",d='<a href="'+b.url()+'" class="'+j+'" target="_blank" data-skimwords-id="'+d+'" data-skimwords-word="'+encodeURIComponent(b.text())+'" data-group-id="'+e+'" data-skim-creative="'+h+'" data-skim-product="'+f+'" title="'+b.text()+'">$1</a>'):(c="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+k+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)",d='$1$2<a href="'+b.url()+'" class="'+j+'" target="_blank" data-skimwords-id="'+d+'" data-skimwords-word="'+
encodeURIComponent(b.text())+'" data-group-id="'+e+'" data-skim-creative="'+h+'" data-skim-product="'+f+'" title="'+b.title()+'">$3$4</a>$5$6');b=c.replace(/\?:/g,"");return{search_regex:RegExp(c,"i"),repl_regex:RegExp(b,"i"),repl_text:d}}function Td(){var b=[],c,d,e={},f,h,j,k=L.get_as_hash_node_dict();Ra||(Ra=[]);for(j in k)if(k.hasOwnProperty(j)&&(node=k[j],node.parentNode&&!oa(node,"noskimwords"))){c=Ud(node,j);d=c[0];for(f=0,h=d.length;f<h;f++)c=d[f],e[c]||(e[c]=1,b.push(c))}b.length?(request_data=
x('{"pubcode":"'+J+'","domains":'+A(b)+"}"),src=""+Za+"?callback=skimwordsUnlinked"+(B?"&dnt="+B:"")+(O?"&fdnt=1":"")+(lb?"&call=toolbar":"")+"&data="+request_data,V(src)):Ga()}function Vd(){var b=0,c,d,e,f,h,j,k,m;c=L.get_as_pair_array();c.sort(function(b,c){return c[1].length-b[1].length});for(e=0,f=c.length;e<f;e++)if(pair=c[e],d=pair[0],h=pair[1],!oa(h,"noskimwords")&&(j=Z.find_matches(d,h))&&j.length){d=dc(j,h,d);d=d[0];for(j=0,k=d.length;j<k;j++)span=d[j],h=span.match,m=span.node,(!Z.maxkeywords()||
b<Z.maxkeywords())&&ec(m,h)&&b++}}function dc(b,c,d,e){var f=y.createDocumentFragment(),h=0,j,k,m,g,n,p=[],l=c.nodeValue,q=[],t=c.parentNode;e||(e="skimwords-potential");null==d&&(d="-1");if(t){for(j=0,k=b.length;j<k;j++)m=b[j],g=y.createElement("span"),g.className=e,n=y.createTextNode(l.substring(h,m.start)),f.appendChild(n),g.innerHTML=m.text,f.appendChild(g),h={},h.node=g,h.match=m,p.push(h),h=m.start+m.text.length,q.push(n),L.add_node(n,d);b=y.createTextNode(l.substring(h));q.push(b);f.appendChild(b);
L.add_node(b,d);t.replaceChild(f,c)}return[p,q]}function fc(b,c){var d=parseInt(b.phrase.action_type()),e=parseInt(c.phrase.action_type()),f=parseFloat(b.phrase.group_priority()),h=parseFloat(c.phrase.group_priority()),j=e-d,k=h-f,m=c.phrase.text().length-b.phrase.text().length;return 8==d||8==e?!j?m:8==d?-1:1:!k?isNaN(f)&&isNaN(h)?m:isNaN(f)?1:isNaN(h)?-1:0:0<k?1:-1}function Sc(b,c){10>parseInt(c)&&(c="0"+c);return"3"+b+"0"+c}function ec(b,c){var d=c.phrase;if(0===d.limit())return!1;Ic||d.dec_limit();
Ib++;Ac++;var e={};e.w=d.text();e.lp=d.url();e.t=Sc(Oa,d.action_type(),d.group_id());e.pid=0===d.group_id()?0:Ec(d.id(),d.action_type());a:{var f,h;h=!0;for(d=0,f=$.length;d<f;d++)if(h=$[d],h=!h.pid&&!h.pid?h.w===e.w:h.pid===e.pid)break a;$.push(e)}pa++;if(!qa){f=(b.data?b.data:b.childNodes[0].data).replace(c.repl_regex,c.replacement);e=y.createElement("span");d=y.createDocumentFragment();e.innerHTML=f;if("msie"===w.browser&&9>w.version&&(f=b.previousSibling,h=/^\s/,f&&f.nodeValue&&f.nodeValue.length&&
h.test(f.nodeValue[f.nodeValue.length-1])&&(f.nodeValue+=" "),(f=b.nextSibling)&&f.nodeValue&&f.nodeValue.length&&h.test(f.nodeValue[0])))f.nodeValue=" "+f.nodeValue;for(;e.firstChild;)e.firstChild.nodeName===$a?(f=d.appendChild(e.firstChild),L.add_node(f)):(f=d.appendChild(e.firstChild),null!=f&&(gc(f,!0),hc(f,!0)));C.create(b).replaceWith(d)}return!0}function Wd(b,c){if(b.length){var d,e,f,h,j=[],k=0,c=Z.maxkeywords()||0,m="msie"===w.browser&&9>w.version;if(m)d=C.create("body").text().length,3E4<
d?c=Math.ceil(d/1E4):m=!1;for(f=0,h=b.length;f<h;f++){var g=b[f];d=g.node;e=g.match;var n=e.phrase.group_priority()?parseFloat(e.phrase.group_priority()):0,p=!1;if(g.match.target_occurence==v(g,"occurence")){if("1"===e.phrase.action_type()||"2"===e.phrase.action_type()||Wb&&n>Wb)p=!0;m&&(p=!0);"17075X740592"===J&&C.create(d).parents(".atma-norules").length&&(p=!0);if(!oa(d,"noskimwords")&&0!==e.phrase.limit()&&Xd(d,j,p)&&(k++,ec(d,e),c&&k>=c))break}}}}function ic(b){var c=0,d=0;if(b.offsetParent){do c+=
b.offsetLeft,d+=b.offsetTop;while(b=b.offsetParent)}return{x:c,y:d}}function Yd(b,c,d){var e=0,f=b.length-1,h,j;for("function"!==typeof d&&(d=function(b,c){return b===c?0:b>c?1:-1});e<=f;)if(h=Math.floor((f+e)/2),j=d(c,b[h]),0<j)e=h+1;else if(0>j)f=h-1;else return{found:!0,index:h};return{found:!1,index:e}}function Xd(b,c,d){function e(b,c){Math.abs(b.x-c.x)<=t&&Math.abs(b.y-c.y)<=r&&(z=!0);return b.y===c.y?b.x-c.x:b.y-c.y}var f,h,j,k,g,s,n,p,l,q;j=ic(b);var t=Fc,r=Gc,z=!1;if(!t&&!r)return!0;t=!t?
0:t;r=!r?4:r;h=[{test:function(b){return 0<b&&b<c.length},count:function(b){return b-1}},{test:function(b){return b<c.length},count:function(b){return b+1}}];f=y.createElement("span");f.style.position="absolute";b.nextSibling?b.parentNode.insertBefore(f,b.nextSibling):b.parentNode.appendChild(f);f=ic(f);f=y.createElement("span");f.style.position="absolute";b.nextSibling?b.parentNode.insertBefore(f,b.nextSibling):b.parentNode.appendChild(f);f=ic(f);b=[j,f];for(k=0;k<b.length;k++){g=b[k];if(z)break;
s=Yd(c,g,e);for(l=0;l<h.length&&!(q=h[l],z);l++)for(n=q.count(s.index);q.test(n);n=q.count(n)){p=c[n];if(!(Math.abs(g.y-p.y)<=r))break;if(Math.abs(g.x-p.x)<=t){z=!0;break}}}if(!d&&z)return!z;h=j.y===f.y?j.x-f.x:j.y-f.y;0<h?h=f:0>h?(h=j,j=f):(h=j,j=null);s.index===c.length?(c.push(h),j&&c.push(j)):j?c.splice(s.index,0,h,j):c.splice(s.index,0,h);return d||!z}function kb(b){if(ra=b)if(""==N&&ra.guid&&(N=ra.guid),ra.lang&&(cb=ra.lang.toLowerCase()),L.is_traversed()||L.traverse(ra.includes,ra.excludes),
Z.store(b),L.length()&&Z.num_nodes()){b=Lc?0:1;if("mozilla"===w.browser){var c=/Firefox\/(\d.\d)/.exec(navigator.userAgent);c&&2<=c.length&&3.7>=parseFloat(c[1])&&(b=0)}else"msie"===w.browser&&8>w.version&&(b=0);if(b){var d=Z.spanify_all();for(b=0,c=d.length;b<c;b++)d[b].orig_i=b;d.sort(function(b,c){var d=fc(b.match,c.match);return d?d:b.orig_i-c.orig_i});Wd(d)}else Vd();d=W("skimwords-link");if("msie"===w.browser&&9>w.version){var e,f,h=/^\s/;for(b=0,c=d.length;b<c;b++){f=d[b];if((e=f.previousSibling)&&
e.nodeValue&&e.nodeValue.length&&h.test(e.nodeValue[e.nodeValue.length-1]))e.nodeValue+=" ";if((e=f.nextSibling)&&e.nodeValue&&e.nodeValue.length&&h.test(e.nodeValue[0]))e.nodeValue=" "+e.nodeValue}}setTimeout(function(){for(var b=W("skimwords-link"),c,d=0,e=b.length;d<e;d++)c=b[d],ac(c),mb&&mb(c);if("17075X740592"===J){b=F(".atma-norules a.skimwords-link");d=0;for(e=b.length;d<e;d++)b[d].style.color="#C9C7C7 !important",b[d].style.fontStyle="normal !important"}},10)}ib||C.create(y).ready(function(){if(!fb){var b=
H.productCSSDomain+gb,c=y.createElement("link");c.rel="stylesheet";c.text="text/css";c.href=b+".css";y.getElementsByTagName("head")[0].appendChild(c);if(ga)b=H.productCSSDomain+"branded-"+ga+".css",c=y.createElement("link"),c.rel="stylesheet",c.text="text/css",c.href=b,y.getElementsByTagName("head")[0].appendChild(c);fb=!0}var b=W("skimwords-link"),d,e,f,h,g,q,t,r,z;if(!("msie"===w.browser&&7>w.version)&&C.support.boxModel)for(c=0,f=b.length;c<f;c++)if(q=b[c],h=parseInt(P(q,"skimwords-id")),t=P(q,
"skimwords-word"),e=[],d=!0,r=Z.group_from_link(q)){if(branded_product=r.branded_product())v(q,"href",branded_product.url()),P(q,"skimwords-id",z.id()),z.id(),d=P(q,"skim-creative").toString(),P(q,"skim-creative",d.charAt(0)+r.flyover_version()+d.charAt(3)+d.charAt(4)+d.charAt(5)),e.push(Oc(branded_product,r,t));else{products=r.get_sorted_products(h);for(h=0,g=products.length;h<g&&h<Zb;h++)z=products[h],-1!==z.url().indexOf(".ebay")&&(d=!1),e.push(Oc(z,r,t));(d=d&&!r.is_multi())&&e.push(Rd(z,t))}v(q,
"title","");e=e.join("");Od(q,e,r.id(),r.is_multi(),r.hover_title(),branded_product)}});"function"==typeof post_skimwords_hook&&post_skimwords_hook();Kc?Ga():Td();Ca=!1;nb&&(Ha=!0,Tc||(Tc=!0,y.getElementsByTagName("body").length&&(y.addEventListener?y.getElementsByTagName("body")[0].addEventListener("DOMNodeInserted",Cc,!1):document.attachEvent&&y.getElementsByTagName("body")[0].attachEvent("DOMNodeInserted",Cc))))}function Fa(b){var c=H.instantApiUrl,d,e="";Ea?e="&filter=lite":Da?e="&filter=standard":
Xb?e="&filter=diy":Yb&&(e="&filter=whitelist");e+="&version=10&js=1";fa?d=encodeURIComponent('{"instant":"1","page":"'+ea+'","pref":"'+R+'","pubcode":"'+J+'"}'):(d=encodeURIComponent('{"page":"'+ea+'","pref":"'+R+'","pubcode":"'+J+'"'+(hb?',"diy":"1"':"")+"}"),c=H.skimwordsApiUrl);V(c+"?callback="+b+"&data="+d+(sw_debug?"&debug="+sw_debug:"")+(0!=B?"&dnt="+B:"")+(O?"&fdnt=1":"")+e)}function Zd(b){var c=null,d=function(){var e=0;return function(){g.jQuery&&g.jQuery!=c?(ma=F=g.jQuery.noConflict(!0),
b(ma)):100>e++&&setTimeout(d,10)}}();if(ma)b(ma);else{try{c=g.jQuery}catch(e){}H||ob();c&&c.fn&&c.fn.jquery&&c.fn.jquery>=H.jQueryMinVersion&&c.fn.jquery<=H.jQueryMaxVersion?(ma=F=c,b(ma)):V(H.jQueryUrl,d)}}function Ia(){Zd(function(){if("msie"===w.browser&&8>w.version)if(Tb)sa=!0;else{var b=/Windows NT (\d.\d)/.exec(navigator.userAgent);b&&2<=b.length&&6>=parseFloat(b[1])&&(ib=!0)}sa||(Ld(),Uc(),"function"==typeof pre_skimwords_hook&&pre_skimwords_hook(),fa||Ea||Da||hb?Fa("instantDataCallback"):
Fa("skimwordsDataCallback"))})}function Uc(){if(g.skimlinksNoRemove)return zc;for(var b=W("skimwords-link"),c=Ib=0,d=b.length;c<d;c++){var e=C.create(b[c]);e.after(e.text());e.remove()}}var ia,Vc,jc,kc,ta,ob,Wc,lc,v,G,Xc,Yc,mc,Sa,Zc,$c,ad,nc,Ta,P,x,na,ha,oc,bd,cd,w,X,ua,ja,Ja,va,pb,Ua,D,wa,xa,ya,ba,I,za,qb,rb,$,pc,dd,sb,W,ed,fd,V,gd,hd,id,K,jd,hc,qc,tb,oa,rc,sc,tc,kd,ld,md,nd,od,pd,A,qd,rd,sd,ub,td,ud,vd,uc,wd,xd,vc,yd,zd,vb,U,Ad,ca,Bd,wb,xb,yb,Va,Wa,Cd,ka,Xa,Ka,wc,zb,da,Ab,Bb,la,La,Q,S,qa,Aa,gc,
bc,Dd,Ga,Ed,Fd,Gd,Cb,Ba,nb,N,cc,B,Ya,O,Ha,Db,sa,J,lb,M,R,Eb,Hd,g,Ma={}.hasOwnProperty,Id=[].indexOf||function(b){for(var c=0,d=this.length;c<d;c++)if(c in this&&this[c]===b)return c;return-1};if(window.skimlinks_revenue_forecast&&window.skimlinks)return!1;va=pb=null;I={pag:"",pub:"",guid:"",uc:"",lnks:{}};D={pag:"",phr:{},pub:"",slc:0,swc:0,jsl:0,jsf:"",guid:"",uc:"",t:1};Ua=/http:/g;w=function(){var b;b=navigator.userAgent.toLowerCase();b=/(webkit)[ \/]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(b)||
/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||[];return{browser:b[1]||"",version:parseFloat(b[2])||0}}();$=[];qb=(new Date).getTime();za=[];rb=[];wa=X=ja=null;Ja=!1;xa=[];ua=[];ya=[];ba={"amazon.co.uk":{country:"gb",regex:[/\/(dp|product)\/([A-Z0-9]+)[\/|\?|$]?/],search:[/keywords=([^&]+)/,/search\-alias=([^&]+)/]},"amazon.de":{country:"de",regex:[/\/(dp|product)\/([A-Z0-9]+)[\/|\?|$]?/],search:[/keywords=([^&]+)/,/search\-alias=([^&]+)/]}};yd=function(){$=
[];qb=(new Date).getTime();za=[];rb=[];X=ja=null;Ja=!1;xa=[];ua=[];return ya=[]};La=la=Ab=Wa=Va=da=S=null;xb=[];Xa=[];ka=Bb=wb=yb=zb=null;Ka=!1;wc="beginning";Q=qa=!1;Db=sa=Ha=J=null;N=cc="";O=B=0;Ya=nb=lb=!1;g=this;M=g.location;R="";ia=!1;xc=["noskim","norewrite"];yc="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");Za="//r.skimresources.com/api/";Cd=function(){return!0};pc=function(b){var c;c=document.createElement("a");
c.href=b;return Aa(c.hostname)};ob=function(){var b,c,d,e,f,h,j,k,m,s,n,p,l,q,t,r,z,v,w,x,y,A,C,E,F,G,H,K;pb=null!=(b=document.getElementsByTagName("html"))?b[0]:void 0;xa=null!=(c=g.skimlinks_included_classes)?c:[];ua=null!=(l=g.skimlinks_excluded_classes)?l:[];ya=null!=(A=g.skimlinks_included_ids)?A:[];va=g.force_location?pc(g.force_location):M.hostname;S=null!=(C=g.skimlinks_tracking)?C:!1;da=g.skimlinks_site||g.skimlinks_sitename||!1;Va=null!=(E=g.skimlinks_domain)?E:"go.redirectingat.com";Wa=
null!=(F=g.skimlinks_google)?F:!1;Ab=null!=Wa?Wa:"skimout";la=null!=(G=g.skimlinks_target)?G:!1;La=null!=(H=g.sl_test)?H:!1;xb=null!=(K=g.skimlinks_exclude)?K:[];Xa=null!=(d=g.skimlinks_include)?d:[];zb=null!=(e=g.skimlinks_noright)?e:!1;yb=null!=(f=g.skimlinks_exrel)?f:!1;wb=null!=(h=g.skimlinks_byrel)?h:!1;Bb=null!=(j=g.skimlinks_blocked_tag)?j:!1;qa=null!=(k=g.skimlinks_revenue_forecast)?k:!1;ka=0;Q=id();g.skimlinks_revenue_forecast=!1;J=null!=(m=g.skimlinks_pub_id)?m:"";if(g.skimlink_legacy_support)g.skimlinks=
function(){return!0},g.mugicPopWin&&(g._mugicPopWin=g.mugicPopWin),g.mugicPopWin=function(){return!0},g.mugicRight=function(){return!0},g.mugicRightClick=function(){return!0};B=null!=(s=g.skimlinks_dnt)?s:0;O=null!=(n=window.skimlinks_nocookie)?n:!1;O=null!=(p=window.skimlinks_nocookie)?p:!1;Ha=null!=(q=g.noimpressions)?q:!1;Db=null!=(t=g.noskimlinks||g.noskim)?t:!1;sa=null!=(r=g.noskimwords||g.noskim)?r:!1;lb=null!=(z=g.skim_toolbar)?z:!1;nb=null!=(v=g.skimlinks_ajax_rerun)?v:!1;Ya=null!=(w=g.skimlinks_ipc)?
w:!1;Ka=null!=(x=g.skimlinks_ipc_decoration)?x:!1;wc=null!=(y=g.skimlinks_ipc_position)?y:"beginning";if(g.document&&g.document.referrer)R=g.document.referrer;nd(va)&&(sa=Db=!0);S&&!/^[a-z0-9_\\|]+$/i.test(S)&&(S=!1);I.pag=D.pag=g.force_location||M.href;I.pub=D.pub=J;I.uc=D.uc=S;"undefined"!==typeof Sb&&null!==Sb&&Sb();ua.push("noskimlinks");return!0};id=function(){var b;return"function"===typeof(b=new Date).getTimezoneOffset?b.getTimezoneOffset():void 0};nd=function(b){var c,d,e,f;if(g.noskim_domains){f=
g.noskim_domains;for(d=0,e=f.length;d<e;d++)if(c=f[d],-1!==b.toLowerCase().indexOf(c.toLowerCase()))return!0}return!1};Aa=function(){var b;b=/^www\./i;return function(c){return c.replace(b,"")}}();G=function(){return document.addEventListener?function(b,c,d){if(b&&(b.nodeName||b===g))return b.addEventListener(c,d,!1)}:function(b,c,d){if(b&&(b.nodeName||b===g))return b.attachEvent("on"+c,function(){return 7>w.version&&!window.event?(setTimeout(function(){return d.call(b,window.event)},100),!0):d.call(b,
window.event)})}}();ha=function(){return document.createElement("div").getElementsByClassName?function(b,c){return K(b,c)?b:b.getElementsByClassName(c)}:function(b,c){var d;d=nc(c);return oc(b,d)}}();x=function(){var b,c;c=[function(){var c,e,f,h;f=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];h=[];for(c=0,e=f.length;c<e;c++)b=f[c],h.push([RegExp(b[0],"g"),b[1]]);return h}()];return function(d){var e,f,d=encodeURIComponent(d);for(e=0,f=c.length;e<f;e++)b=
c[e],d=d.replace(b[0],b[1]);return d}}();tc=function(){var b;b=/^\/\/|https?:\/\//i;return function(c,d){return b.test(c)&&(!d||!va||-1===d.indexOf(va))&&(!va||-1===va.indexOf("."+d))}}();v=function(b,c,d){var e;3<=arguments.length&&("undefined"!==typeof b.setAttribute?b.setAttribute(c,d):b[c]=d);try{return e=b[c],null==e&&(e=b.getAttribute(c)),e}catch(f){return null}};P=function(b,c,d){arguments[1]="data-"+c;return v.apply(this,arguments)};bc=function(b,c){var d;d=b.innerText||b.textContent||b.nodeValue;
if(2<=arguments.length)"undefined"!==typeof b.innerText?b.innerText=c:b.textContent=c,d=c;return d};Ba=function(){var b,c;if(String.prototype.trim)return function(b){return null===b?"":String.prototype.trim.call(b)};b=/^\s+/;c=/\s+$/;/\S/.test("\u00a0")&&(b=/^[\s\xA0]+/,c=/[\s\xA0]+$/);return function(d){return null===d?"":d.toString().replace(b,"").replace(c,"")}}();Vc=function(b,c){return!K(b,c)?(b.className+=" "+c,!0):!1};qd=function(b){var c,d,e,f,h;if("object"===typeof b||b instanceof Array){f=
"";e=0;d=b instanceof Array;for(h in b)Ma.call(b,h)&&(c=b[h],0<e&&(f+=","),d?f+=A(c):(c=A(c),f+='"'+h+'":'+c),e++);return d?"["+f+"]":"{"+f+"}"}return"string"===typeof b?(c=b.replace(/"/g,'\\"',b),'"'+c+'"'):isNaN(b)?"null":b.toString()};A=function(){var b;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(b=JSON.stringify,function(c){return b(c)}):qd}();na=function(){var b,c;b=/[-[\]{}()*+?.,\\^$|#\s]/g;c=/\s+/g;return function(d){return d.replace(b,
"\\$&").replace(c,"s+")}}();nc=function(b){b=na(b);return RegExp("\\b"+b+"\\b","i")};K=function(b,c){return b.className?nc(c).test(b.className):!1};oc=function(b,c){var d,e,f,h,j;e=[];b.className&&c.test(b.className)&&e.push(b);j=b.childNodes;for(f=0,h=j.length;f<h;f++)d=j[f],e=e.concat(oc(d,c));return e};Zc=function(b){return-1!==encodeURIComponent(b).indexOf("%C3%82%C2%A3")};cd=function(b){b=b.innerHTML.slice(0,4);if("http"===b||"www."===b)b.innerHTML="<span style='display:none!important;'>&nbsp;</span>";
return!0};od=function(b){for(var c,d,e,f,b=b.parentNode;b&&b!==pb;){d=b.id;for(e=0,f=xa.length;e<f;e++)if(c=xa[e],K(b,c))return!1;for(e=0,f=ya.length;e<f;e++)if(c=ya[e],d===c)return!1;for(d=0,e=ua.length;d<e;d++)if(c=ua[d],K(b,c))return!0;b=b.parentNode}return xa.length||ya.length?!0:!1};oa=function(b,c,d){null==d&&(d=!1);for(c=RegExp("\\b(?:(?:"+na(c)+")|(?:noskim))\\b","i");null!=b&&b!==pb;){if(b.className&&c.test(b.className))return!0;b=d?null:b.parentNode}return!1};$c=function(b,c){var d,e,f,
h,j;h=R?"&pref="+x(R):"";K(b,"skimwords-link")||K(b,"skimwords-unlinked")?(j=K(b,"skimwords-link")?v(b,"data-skimwords-word"):"url",d=v(b,"data-skim-creative"),e=v(b,"data-skim-product"),f=g.skimlinks_domain||"go.redirectingat.com","undefined"!==typeof H&&null!==H&&(f=H.sw_domain||f),c="http://"+f+"/?id="+J+""+(S?"&xcust="+S:"")+"&xs=2&url="+x(c)+"&xguid="+N+"&isjs=1&xword="+(j?j:"")+"&xcreo="+(d?d:"")+"&xpid="+(e?e:"")+"&sref="+x(M)+""+h+""+(B?"&dnt="+B:"")+""+(O?"&fdnt=1":"")+""+(!1!==Q?"&xtz="+
Q:"")):K(b,"skimlinks-inline")?(d=v(b,"data-skim-creative"),c="http://"+Va+"/?id="+J+""+(da?"&site="+da:"")+""+(La?"&test="+La:"")+""+(S?"&xcust="+S:"")+"&xs=8&isjs=1&url="+x(c)+"&xguid="+N+"&xcreo="+(b&&null!=d?d:0)+"&sref="+x(M)+"&pref="+x(R)+""+(B?"&dnt="+B:"")+""+(O?"&fdnt=1":"")+""+(!1!==Q?"&xtz="+Q:"")):oa(b,"noskimlinks")||(d=v(b,"data-skim-creative"),c="http://"+Va+"/?id="+J+""+(da?"&site="+da:"")+""+(La?"&test="+La:"")+""+(S?"&xcust="+S:"")+"&xs=1&isjs=1&url="+x(c)+"&xguid="+N+"&xcreo="+
(b&&null!=d?d:0)+"&sref="+x(M)+""+h+""+(B?"&dnt="+B:"")+""+(O?"&fdnt=1":"")+""+(!1!==Q?"&xtz="+Q:""));ia&&(c+="&abp=1");return c};sb=function(b){var c;if((c=b.target||b.srcElement)&&!c.href&&b.currentTarget)c=b.currentTarget;for(;c&&"A"!==c.nodeName;)c=c.parentNode;return c};U=function(b){var c;c=sb(b);vc(c);if(g.vglnk&&K(c,"skimwords-link"))b&&b.stopPropagation?b.stopPropagation():(b=g.event,b.cancelBubble=!0);return!0};vc=function(b){var c,d,e,f,h;f="msie"===w.browser&&7>w.version?1E4:300;c=Wa;
if(b&&b.nodeName&&"IMG"===b.nodeName)b=b.parentNode;if(b){h=b.href;d="http://"+Va;if(h.length>=d.length&&h.substr(0,d.length)===d)return!0;if("msie"===w.browser&&b.childNodes.length&&3===b.childNodes[0].nodeType)e=b.innerHTML;d=-1!==h.indexOf(d)?h:$c(b,h);c&&Dd(h);P(b,"skimlinks-orig-link")||P(b,"skimlinks-orig-link",h);b.href=d;setTimeout(function(){b.href=P(b,"skimlinks-orig-link");P(b,"skimlinks-orig-link","");if(e)b.innerHTML=e;return!0},f)}return!0};rc=function(b,c){var d,e;null==c&&(c=rb);if(c)for(d in c)if(Ma.call(c,
d)&&(e=c[d],e===b))return!0;return!1};md=function(b,c){return qa?(rc(b,c)&&(ka+=1),!1):rc(b,c)};pd=function(b){var c,d;if(!Bb)return!1;c=null!=b?b.previousSibling:void 0;if(!c)return!1;b=("["+Bb+"]").toLowerCase();d=bc(c);d=d.toLowerCase();d=Ba(d);c=d.lastIndexOf(b);return-1!==c&&c+b.length===d.length};tb=function(b){return!b||wb&&b===wb||!jd(b)};jd=function(b){var c,d,e,f;ja=null;if(!b)return!1;b=b.toLowerCase();if(ja)return ja[b];ja={};c=yb?[yb]:[];c=c.concat(xc);for(d=0,e=c.length;d<e;d++)f=c[d],
ja[f.toLowerCase()]=!0;return ja[b]};mc=function(){var b,c,d,e;X={};wa={};da&&xb.push(da);e=xb.concat(yc);for(c=0,d=e.length;c<d;c++)b=e[c],X[b]=b.length;for(c=0,d=Xa.length;c<d;c++)b=Xa[c],wa[b]=b.length;return X};sc=function(b){var c,d,e;(null===X||null===wa)&&mc();if(!b)return!1;for(c in X)if(Ma.call(X,c))if(d=X[c],0===c.indexOf("*")){if(c=c.substr(1),d-=1,e=b.lastIndexOf(c),-1!==e&&e===b.length-d)return!0}else if(b===c)return!0;return!1};kd=function(b){var c,d,e;(null===X||null===wa)&&mc();if(!b)return!1;
if(0===Xa.length)return!0;for(c in wa)if(Ma.call(wa,c))if(d="*"===c.substr(0,1),e="*"===c.substr(c.length-1,1),c=c.replace(/\*/g,""),d&&e){if(-1!==b.indexOf(c))return!0}else if(d){if(b.indexOf(c)===b.length-c.length-1)return!0}else if(e){if(0===b.indexOf(c))return!0}else if(b===c)return!0;return!1};qc=function(b,c){return tc(b,c)&&!sc(c)&&kd(c)};Dd=function(b){var c,d,e;c=g.pageTracker;e=g.urchinTracker;d="/"+Ab+"/"+b;if(null!=c&&c._trackPageview)return c._trackPageview(d),!0;if(e)return e(d),!0;
if(g._gaq)c=g._gaq,c.push(["_trackEvent",Ab,"click",b]);return!1};ad=function(b,c){var d,e;null==b&&(b={});null==c&&(c="track.php");for(d in D)Ma.call(D,d)&&(e=D[d],b[d]=e);qa&&(b.xrf=1);d={data:x(A(b).replace(Ua,""))};B&&(d.dnt=B);O&&(d.fdnt=1);ia&&(d.abp=1);return jc(d,"//t.skimresources.com/api/"+c)};Ta=function(b){var c,d;d=x('},"pub"');c=ad();null!=b&&b.length&&(b.join(x(",")),c=c.replace(d,""+b+d));return[c,c.length]};rd=function(b){var c,d,e,f,h;I.tz=Q;I.guid=N;I.pref=R;I.lnks=[];I.typ="s";
c=8E3;"msie"===w.browser&&(c=2E3);d="//t.skimresources.com/api/ipc?data=";for(f=0,h=b.length;f<h;f++)e=b[f],I.lnks.push(e),e=d+x(A(I)),e.length>c&&(I.lnks=I.lnks.slice(0,-1));I.lnks.length&&(d+=x(A(I)),V(d,!1,{async:!0}));return!0};Ed=function(b){var c;if(Ha)return!1;I.tz=Q;I.guid=N;I.pref=R;I.lnks=b;I.typ="s";c={data:A(I)};c=Sa(c);(ia||!ub("//t.skimresources.com/api/ipc",c,Cb))&&rd(b);return!0};vd=function(){return Hd()};Hd=function(){var b,c,d,e,f,h,j,k;f=(new Date).getTime()-qb;e=[];c=8E3;"msie"===
w.browser&&(c=2E3);D.tz=Q;D.slc=ka;D.swc="undefined"!==typeof pa&&null!==pa?pa:0;D.jsl=f;D.guid=N;D.pref=R;D.phr={};f=$;b=Ta();b=b[1];for(d=j=0,k=f.length;j<k;d=++j)if(h=f[d],h=A(h).replace(Ua,""),d=x('"'+d+'":'+h),!("msie"===w.browser&&d.length>c)){b=b+d.length+3*e.length;if(b>c)b=Ta(e),e=b[0],V(e,!1,{async:!0}),e=[],D.t=0,b=Ta(),b=b[1];e.push(d)}c=Ta(e)[0];"msie"===w.browser&&7>w.version&&(c=c.substring(0,4095));V(c,!1,{async:!0});return vb(1)};Cb=function(){return!0};Ga=function(){var b,c,d,e,
f,h;if(Ha)return!1;b=(new Date).getTime()-qb;D.tz=Q;D.slc=ka;D.swc="undefined"!==typeof pa&&null!==pa?pa:0;D.jsl=b;D.guid=N;D.pref=R;D.phr=$;e=D;d={};for(b=f=0,h=$.length;f<h;b=++f)c=$[b],d[""+b]=c;e.phr=d;b={data:A(e)};B&&(b.dnt=B);O&&(b.fdnt=1);b=Sa(b);if(ia||!ub("//t.skimresources.com/api/track.php",b,Cb))return vd(),!0;null!=g.skimlinks_runner&&(g.skimlinks_runner.tracking=1);vb(1);return!0};vb=function(b){if(10>b)return za=zd(),setTimeout(function(){return vb(b+1)},2E3*b)};zd=function(){var b,
c,d,e,f,h,j;c={};e=[];d=[];for(f=0,h=za.length;f<h;f++)b=za[f],b.parentNode?d.push(b):c[b.href]=1;j=W();for(f=0,h=j.length;f<h;f++)b=j[f],c[b.href]&&e.push(b);lc(e);return e.concat(d)};jc=function(b,c){var d,e,f;e=[];qa&&(b.xrf=1);for(d in b)Ma.call(b,d)&&(f=b[d],"data"!==d&&e.push(""+d+"="+f));b.data&&e.push("data="+b.data);return c+"?"+e.join("&")};Gd=function(b){b={call:"track",data:x('{"pubcode":"'+J+'","referrer":"'+M+'","pref":"'+R+'","site":"'+da+'","url":"'+b+'","custom":"'+S+'","xtz":'+Q+
',"product":"1"}')};B&&(b.dnt=B);O&&(b.fdnt=1);b=jc(b,Za);b=b+"&rnd="+Math.random();ed(b);return!0};uc=function(b){b=sb(b).href;Gd(b);return!0};ed=function(b){var c,d;c=document.getElementsByTagName("body")[0];d=document.createElement("img");d.src=b;d.width=1;d.height=1;d.style="display:none";c.appendChild(d);return d};V=function(b,c,d){var l;var e,f,h,j,k,g=this;null==d&&(d={});e=d.charset||null;k=d.target||null;l=null!=(f=d.async)?f:!0,d=l;f=null!=k&&k.document?k.document:document;h=f.getElementsByTagName("head")[0];
j=f.createElement("script");j.type="text/javascript";if(e)j.charset=e;if(c)j.onload=j.onreadystatechange=function(){var b;b=!1;return function(){var d;d=g.readyState;if(!b&&(!d||"complete"===d||"loaded"===d))return j.onload=j.onreadystatechange=null,b=!0,c.call(k),!0}}();j.async=!1!==d;j.src=b;h.appendChild(j);return j};W=function(b){var c,d,e,f,h;c=null;b&&(c=RegExp("\\b"+na(b)+"\\b","i"));h=[];f=document.getElementsByTagName("a");for(d=0,e=f.length;d<e;d++){b=f[d];try{b.href&&(!c||b.className&&
c.test(b.className))&&h.push(b)}catch(j){}}return h};ld=function(b){return-1!==b.indexOf("itunes.apple.com")||-1!==b.indexOf("itunes.com")||-1!==b.indexOf("phobos.apple.com")?!0:!1};lc=function(b){var c,d,e,f,h,j,k,g,s;d=xa.length||ya.length||ua.length;f=[];for(g=0,s=b.length;g<s;g++)if(c=b[g],e=Aa(c.hostname),c.sl_hidden_domain&&(e=Aa(c.sl_hidden_domain)),k=Ba(c.href),j=v(c,"rel"),h=v(c,"onclick"),v(c,"sl-processed",1),c["sl-processed"]=1,(!d||!od(c))&&!pd(c))if(md(e)||ld(k)){if(tb(j)){la&&v(c,"target",
la);if("msie"===w.browser){if(Zc(k))continue;cd(c)}null!=h&&-1!==h.toString().indexOf("return false")?G(c,"click",wd):G(c,"click",U);gc(c,!1);hc(c);f.push(c);zb||G(c,"contextmenu",U);Cd(c)}}else tc(k,e)&&!sc(e)&&tb(j)&&(la&&v(c,"target",la),G(c,"click",uc),zb||G(c,"contextmenu",uc));return f};wd=function(b){var c;c=sb(b);if(g._mugicPopWin)return g._mugicPopWin(c);U(b);return(la?window.open(c.href):window.open(c.href,la)).focus()};hc=function(b,c){var d,e,f,h,j,k,m,s,n;if(g.link_icon||0<b.getAttribute("data-skim-product")&&
g.skimwords_product_icon){if(0<b.getElementsByTagName("img").length)return!0;if("msie"===w.browser&&8>w.version)b.style.display="inline-block";h=e="";null!=c&&(e=g.skimwords_icon_class||"",h=g.skimwords_icon_link_class||"");j=v(b,"title").replace("'","&#39;");f=g.link_icon||g.skimwords_product_icon;K(b,"skimwords-unlinked")||K(b,"skimwords-link")?(k='data-skim-creative="'+P(b,"skim-creative")+'"',m='data-group-id="'+P(b,"group-id")+'"',n='data-skimwords-word="'+P(b,"skimwords-word")+'"',s='data-skimwords-id="'+
P(b,"skimwords-id")+'"',d=K(b,"skimwords-unlinked")?"skimwords-unlinked":"skimwords-link"):d=s=n=m=k="";d="<a href='"+v(b,"href")+"' title='"+j+"' "+k+" "+m+" "+n+" "+s+"style='border:0px;padding:0;margin:0' class='skimlinks-icon-link "+h+" "+d+"' skimlinked='skimlinked' target='_blank'><img src='"+f+"' class='"+e+"' skimlinked='skimlinked' style='margin: 0px 0px -3px 2px !important; float:none !important;  border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;' /></a>";
e=document.createElement("div");e.innerHTML=d;d=e.childNodes[0];G(d,"mousedown",U);b.appendChild(d)}return!0};Yc=function(b,c){var d,e;e="GBP"===b.currency?"&pound;":"EUR"===b.currency?"&euro;":"$";d=document.createElement("a");v(d,"href",b.url);v(d,"title",b.title);v(d,"target","_blank");Vc(d,"skimlinks-inline");v(d,"data-skim-creative",c);d.innerHTML=b.search?"Search on "+b.merchant:""+b.merchant+" "+e+b.price;G(d,"mousedown",U);return d};hd=function(b,c){return null!=b.currentStyle?b.currentStyle[c]:
window.getComputedStyle?document.defaultView.getComputedStyle(b,null).getPropertyValue(c):!1};Xc=function(b,c,d,e,f){return"8"+("text"===b?"1":"cross"===b?"2":"blink"===b?"3":"0")+c+d+(e-1)+f};dd=function(b,c){var d,e,f,h,j,k,g;d=c.price;if(!d)return"0";e=0;f=1E8;j=0;for(k=0,g=b.length;k<g;k++)h=b[k],h=parseFloat(h.price),h>e&&(e=h),parseFloat(h)<f&&(f=h),h===d&&j++;return 1<j?"4":d>=e?"3":d<=f?"1":"2"};kc=function(b,c,d,e,f,h,j,k){var g,s,n,p,l,q,t,r,z,w;s=!0;p=c;n=!1;"end"===wc&&-1!==d[0].url.indexOf(k)&&
d.reverse();f.hasOwnProperty(e)?(k=f[e],h[k].cnt++):(j[e]={},k={},k.lpid=e,k.cnt=1,k.url=c.href.replace(Ua,""),k.prd=[],h.push(k),k=h.length-1,f[e]=k);"cross"===Ka?v(c,"style","text-decoration: line-through !important;"):"text"===Ka?null!=c.parentNode&&(f=null!=(q=hd(c.parentNode,"color"))?q:"#000",v(c,"style","color: "+f+" !important; text-decoration: none !important;")):"blink"===Ka&&v(c,"style","text-decoration: blink !important;");f=d.length;q=0;for(z=0,w=d.length;z<w;z++){l=d[z];n=!0;r=l.currency+
l.price+l.url+l.title+l.merchant;q+=1;g=dd(d,l);g=Xc(Ka,g,f,b,q);if(!j[e].hasOwnProperty(r))t={},t.cur=l.currency,t.mn=l.merchant,t.mid=l.merchant_id,t.pr=l.price,t.ti=l.title,t.pu=l.url.replace(Ua,""),t.cr=g,h[k].prd.push(t),j[e][r]=!0;l=Yc(l,g);s?(r=document.createTextNode(" ("),s=!1):r=document.createTextNode(" | ");p.parentNode.insertBefore(r,p.nextSibling);r.parentNode.insertBefore(l,r.nextSibling);p=l}s||(b=document.createTextNode(") "),p.parentNode.insertBefore(b,p.nextSibling));v(c,"ipc-added",
1);return n};xd=function(b,c){var d,e,f,h,j,g,m,s,n,p,l,q;m=W();s={};f=!1;g=[];j={};for(l=0,q=m.length;l<q;l++)d=m[l],n=v(d,"product-ref"),p=v(d,"search-term"),h=v(d,"ipc-added"),e=Aa(d.hostname),h||(n&&b.hasOwnProperty(n)&&kc(1,d,b[n],n,j,g,s,e)&&(f=!0),!n&&p&&c.hasOwnProperty(p)&&kc(2,d,c[p],p,j,g,s,e)&&(f=!0));if(f)return Ed(g)};Bd=function(){"undefined"!==typeof Ia&&null!==Ia&&!sa?Ia():Ga();return!0};fd=function(b,c){var d,e,f;for(e=0,f=c.length;e<f;e++)if(d=c[e],(d=b.match(d))&&2<d.length)return d[2];
return!1};gd=function(b,c){var d,e,f;for(e=0,f=c.length;e<f;e++)if(d=c[e],(d=b.match(d))&&1<d.length)return d[1]=decodeURIComponent(d[1]),d[1]=d[1].replace(/\+/g," "),d[1];return!1};bd=function(){var b,c,d,e,f,h,j,g,m,s,n,p,l,q;f=W();d=[];e={};g=[];m={};n=[];p={};for(l=0,q=f.length;l<q;l++)b=f[l],c=Aa(b.hostname),s=Ba(b.href),h=v(b,"rel"),qc(s,c)&&tb(h)&&(Ya&&ba.hasOwnProperty(c)&&!K(b,"skimwords-link")&&!K(b,"skimlinks-inline")&&(h=fd(s,ba[c].regex),s=gd(s,ba[c].search),h&&(v(b,"product-ref",h),
j=h+"|"+ba[c].country,m[j]||(h={r:h,c:ba[c].country,d:c},g.push(h),m[j]=!0)),s&&(v(b,"search-term",s+"|"+ba[c].country),b=s+"|"+ba[c].country,p[b]||(s={r:s,c:ba[c].country,d:c},n.push(s),p[b]=!0))),c&&!e[c]&&(d.push(c),e[c]=!0));return{domains:d,product_refs:g,search_terms:n}};Wc=function(){var b;b=document.getElementsByTagName("body");if(0<b.length)return G(b[0],"click",ta),G(b[0],"contextmenu",ta)};ta=function(b){var c,d,e;if(g.event)b=g.event;d=b.originalTarget||b.srcElement;c=v(d,"sl-processed")||
0;null==d["sl-processed"]&&(c=0);if((e=v(d,"class"))&&(-1!==e.indexOf("skimwords-link")||-1!==e.indexOf("skimlinks-inline")||-1!==e.indexOf("skimwords-unlinked")))c=!0;if(("IMG"===(null!=d?d.nodeName.toUpperCase():void 0)||"BUTTON"===(null!=d?d.nodeName.toUpperCase():void 0))&&d.parentNode)d=d.parentNode;if("A"===(null!=d?d.nodeName.toUpperCase():void 0)&&0===c)if(c=d,d=!0,!c||!c.href?d=!1:0!==c.href.indexOf("http://")&&0!==c.href.indexOf("https://")&&0!==c.href.indexOf("//")&&(d=!1),d&&qc(c.href,
Aa(c.hostname))){vc(c);if(g.vglnk&&K(c,"skimwords-link"))b&&b.stopPropagation?b.stopPropagation():(b=g.event,b.cancelBubble=!0);return!0}};sd=function(b){var c,d,e,f,h,j;c=8E3;"msie"===w.browser&&(c=2E3);f={};f.pub=J;f.pag=M.href;f.tz=Q;f.dl=[];f.typ="l";d="//t.skimresources.com/api/link?data=";for(h=0,j=b.length;h<j;h++)e=b[h],f.dl.push(e),e=d+x(A(f)),e.length>c&&(f.dl=f.dl.slice(0,-1));f.dl.length&&(d+=x(A(f)),V(d,!1,{async:!0}));return!0};Fd=function(b){var c;if(Ha)return!1;c={};c.pub=J;c.pag=
M.href;c.dl=b;c.tz=Q;c.typ="l";c={data:A(c)};B&&(c.dnt=B);O&&(c.fdnt=1);c=Sa(c);if(ia||!ub("//t.skimresources.com/api/link",c,Cb))return sd(b)};td=function(b,c,d){var e,f,h,j,g,m;e=x('{"pubcode":"'+J+'","domains":_DOMAIN_LIST__PRODUCT_REFS__SEARCH_TERMS_,"page":"'+M.href+'"}');j=""+Za+"?callback=skimlinksApplyHandlers"+(B?"&dnt="+B:"")+(O?"&fdnt=1":"")+(lb?"&call=toolbar":"")+"&data="+e;e="msie"===w.browser?2E3:8E3;h=[];for(g=0,m=b.length;g<m;g++)f=b[g],h.push(f),j.replace("_DOMAIN_LIST_",x(A(h))).length>
e&&(h=h.slice(0,-1));j=j.replace("_DOMAIN_LIST_",x(A(h)));if(Ya){b=[];for(h=0,g=c.length;h<g;h++)f=c[h],b.push(f),j.replace("_PRODUCT_REFS_",',"product_refs":'+x(A(b))).length>e&&(b=b.slice(0,-1));j=j.replace("_PRODUCT_REFS_",',"product_refs":'+x(A(b)));c=[];for(f=0,h=d.length;f<h;f++)b=d[f],c.push(b),j.replace("_SEARCH_TERMS_",',"search_terms":'+x(A(c))).length>e&&(c=c.slice(0,-1));j=j.replace("_SEARCH_TERMS_",',"search_terms":'+x(A(c)))}else j=j.replace("_PRODUCT_REFS_",""),j=j.replace("_SEARCH_TERMS_",
"");return V(j)};Sa=function(b){var c,d;c=[];qa&&(b.xrf=1);for(d in b)b.hasOwnProperty(d)&&c.push(""+d+"="+x(b[d]));return c.join("&")};ub=function(b,c,d){var e,f,h;if("msie"!==w.browser)f=!1,h=new XMLHttpRequest,h.open("POST",b,!0),h.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=Id.call(h,"withCredentials")&&(h.withCredentials=!0),h.async="true",h.onreadystatechange=function(){var b;if(f)return!0;if(4===h.readyState){f=!0;if(200===h.status){b={};try{b=JSON.parse(h.responseText)}catch(c){try{b=
eval("("+h.responseText+")")}catch(e){b={}}}d(b);return!0}return!1}},h.send(c);else if(g.XDomainRequest){if(e=new XDomainRequest,0<=Id.call(e,"withCredentials")&&(e.withCredentials=!0),e){e.open("POST",b,!0);e.onload=function(){var b;b={};if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{b=JSON.parse(e.responseText)}catch(c){b={}}else try{b=eval("("+e.responseText+")")}catch(f){b={}}d(b);return!0};e.onerror=function(){return!1};e.onprogress=function(){return!1};e.ontimeout=function(){return!1};
e.async=!0;try{e.send(c)}catch(j){return!1}}}else return!1;return!0};ud=function(b,c,d){var e;e={data:A({pubcode:J,domains:b,product_refs:c,search_terms:d,page:M.href})};Sa(e);td(b,c,d);return!0};Eb=function(){var b;if(window.skimlinksInitialized&&"function"!==typeof post_skimwords_hook)return!0;window.skimlinksInitialized=!0;ob();nb&&Wc();Db?"undefined"!==typeof Ia&&null!==Ia&&!sa?Ia():Ga():(b=bd(),ud(b.domains,b.product_refs,b.search_terms),Fd(b.domains));return!0};ca=function(){if(Ja)return!1;
Ja=!0;$d.detect(function(b){ia=b;return Eb()});return!0};gc=function(b,c){var d,e;e=b.style.cssText;e+=" ";if(g.link_background)d=g.link_background,-1===d.indexOf("#")&&(d="#"+d),e+="background-color: "+d+" !important; ";if(null!=g.link_tooltip)b.title=g.link_tooltip;if(c){if(g.skimwords_color)d=g.skimwords_color,-1===d.indexOf("#")&&(d="#"+d),e+="color: "+d+" !important; ";g.skimwords_weight&&(e+="font-weight: "+g.skimwords_weight+" !important; ");if(g.skimwords_decoration)d=g.skimwords_decoration,
e="double"===d?e+"border-bottom: 1px double !important; ":"dashed"===d?e+"border-bottom: 1px dashed !important; ":e+("text-decoration: "+d+" !important; ");if(g.skimwords_style)d=g.skimwords_style,e+="text-style: "+d+"; ";if(g.skimwords_link_style)d=g.skimwords_link_style,e+=d+"; ";d=" "+b.className;if(g.skimwords_link_class)d+=" "+g.skimwords_link_class,b.className=d.substring(1);if(g.skimwords_title)b.title=g.skimwords_title;if(null===b.getAttribute("title"))b.title="Shopping link added by SkimWords";
if(b.getAttribute("data-skim-creative")&&(d=parseInt(b.getAttribute("data-skim-creative"))%10,1===d||2===d))b.title=""}b.style.cssText=e;return!0};Ad=function(){return function(){var b,c,d;c=function(){if(Ja)return!0;try{document.documentElement.doScroll("left")}catch(b){return setTimeout(c,50),!1}return ca()};b=function(){return document.addEventListener?function(){document.removeEventListener("DOMContentLoaded",b,!1);ca();return!0}:document.attachEvent?function(){document.detachEvent("onreadystatechange",
b);ca();return!0}:function(){ca();return!0}}();if("complete"===document.readyState)setTimeout(ca,1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",b,!1),g.addEventListener("load",ca,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",b);g.attachEvent("onload",ca);d=!1;try{d=null===g.frameElement}catch(e){}document.documentElement.doScroll&&d&&c()}return!0}}();g.skimlinksApplyHandlers=function(b){var c,b=null!=b?b:{};null!=g.skimlinks_runner&&
(g.skimlinks_runner.skimlinks=1);c=W();b.country&&(cc=b.country);b.guid&&""===N&&(N=b.guid);if(Ya)b.hasOwnProperty("products")||(b.products=[]),b.hasOwnProperty("search_terms")||(b.search_terms=[]),xd(b.products,b.search_terms);rb=b.merchant_domains;za=lc(c);ka+=za.length;Bd();return!0};g.skimlinksAjaxHandlerByClass=function(b){var c,d,e;if("function"===typeof document.getElementsByClassName){c=document.getElementsByClassName(b);for(d=0,e=c.length;d<e;d++)b=c[d],G(b,"click",ta),G(b,"contextmenu",
ta);return!0}return!1};g.skimlinksAjaxHandlerById=function(b){return(b=document.getElementById(b))?(G(b,"click",ta),G(b,"contextmenu",ta),!0):!1};!g.mugicPopWin&&!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.mugicPopWin=U);!g.mugicRight&&!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.mugicRight=U);g.skimlinksReload=function(){Ja=!1;ca();return!0};!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.skimlinks=Eb);var $d=new function(b){function c(b,d){f||1E3<
d?"function"==typeof b&&(f?e?b(!0):b(!1):b(!1)):setTimeout(c,d*=2,b,d)}function d(){f||(h.complete&&g.complete&&(f=!0),f&&"0"!=h.width&&"0"==g.width&&(e=!0))}var e=!1,f=!1,h=null,g=null;this.detect=function(b){c(b,250)};(function(){try{var c=navigator.userAgent.toLowerCase();if(-1==c.indexOf("firefox")&&-1==c.indexOf("chrome")){f=!0;e=!1;return}}catch(m){}c=11*Math.random();h=new Image;h.onload=d;h.src=b.replace(/\*/,1).replace(/\*/,c);g=new Image;g.onload=d;g.src=b.replace(/\*/,2).replace(/\*/,c)})()}("//p.skimresources.com/px.gif?ch=*&rn=*"),
y,H,zc,Gb,Fb,Na,E,C,Hb,Nc,T,ab,Y,F,ma,pa=0,Ea,Da,fa,Oa,bb,gb,cb,Fc,Gc,Tb,Hc,Ic,ra,ea,Ac,Ib,eb,db,Jb,Kb,Lb,Mb,Nb,Ob,Ub,Vb,Wb,ga,$b,Jc,hb,Xb,Yb,ib,Kc,Zb,Lc,fb,Mc,mb,$a,Ra,Tc=!1,Qb=0,Pb=null,Ca=!1,Rb=0,L=function(){function b(b,d){var f=b.nodeName===$a?C.trim(b.nodeValue):null,d=d||!1,g;if(g=f)g=Ba(f),g=!(g&&"<"===g[0]);if(g){if(d&&"-1"===d)return!1;var s;if(f){d?g=d:(g=Ba(f.replace(/\s+/g," ")).length,s=f.replace(/[:\s]*/g,""),g=""+g+":"+s.substring(0,20));if(c[g]){for(;20>g.length;)g+=" ";g+=" "+e++}d=
g}else d="";if(!d)return!1;c[d]=b}return f?!0:!1}var c={},d=!1,e=1,f=function(){return function(b){return-1!==",p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section,".indexOf(","+b.nodeName.toLowerCase()+",")}}();return{traverse:function(e,g,k){var m,e=e||[],g=g||[];if(c&&c.length&&!k)return c;var s,n,p,l,q,t,r,v,k=[];d=!0;m=[];s=C.create("body");l=g;l.push("div.widget-content");
l.push("div.googleAdText");l.push("div[id=ad]");l.push("div[id=banner]");l.push("div[id=advertisement]");l.push("div[id=adv_container]");l.push("div.ad");l.push("div.banner");l.push("div.advertisement");l.push("div.ad_container");l.push("span.IL_AD");l.push("div[id=fave-ext-container]");-1!=M.href.indexOf(".google.")?(l.push("td.gac_c"),l.push("table[id=mbEnd]"),l.push("div[id=mbEnd]"),l.push("span[id=taw]"),l.push("td.std"),l.push("div.std"),l.push("table.gssb_e"),l.push("div.c"),l.push("div[id=tads]")):
-1!=M.href.indexOf(".yahoo.")?(l.push("ul.spns,ul.reducepx-spnslist"),l.push("ul[class*=reducepx-spnslist]"),l.push("ul[id=east]")):-1!=M.href.indexOf(".aol.")?(l.push("div.sllLink"),l.push("div.n")):-1!=M.href.indexOf(".bing.")&&(l.push("div.sb_adsW"),l.push("div[id=sidebar]"),l.push("div.sb_adsWv2"),l.push("div.sb_adsNv2"),l.push("div[class*=sb_ads]"));for(q=0,t=g.length;q<t;q++)g[q]=Qc(g[q]);q=g.join(",").replace("class=","class^=");if(s.find(q).size()){l=!0;m=[];for(q=0,t=g.length;q<t;q++)s.find(g[q]).size()&&
m.push(g[q]);q=m.join(",").replace("class=","class^=")}else l=!1;delete m;delete s;g=l;m=q;0===e.length&&e.push("body");for(q=0,l=e.length;q<l;q++){inc=Qc(e[q]);v=C.create(inc);for(t=0,r=v.length;t<r;t++)for(k.push(v[t]);0<k.length;)if(s=k.shift())if(n=C.create(s),(!g||!n.is(m))&&!Pc(n)&&!oa(s,"noskimwords",!0))if(s.hasChildNodes())for(p=0,l=s.childNodes.length;p<l;p++)(n=s.childNodes[p])&&n.nodeName&&!b(n)&&f(n)&&k.push(n);else b(s)}},traverse_node:function(c){var d=[];for(d.push(c);0<d.length;)if(node=
d.shift())if(noquery_node=C.create(node),!Pc(noquery_node)&&!oa(node,"noskimwords",!0))if(node.hasChildNodes()){children_to_callback=[];for(i=0,il=node.childNodes.length;i<il;i++)(child=node.childNodes[i])&&child.nodeName&&!b(child)&&f(child)&&d.push(child)}else b(node)},is_traversed:function(){return d},get_non_colliding_nodes:function(){var b,d,e=c,f={};Rb=0;for(b in e)e.hasOwnProperty(b)&&(d=Bc(b),f[d]=e[b],Rb++);return f},reset:function(){c=[];d=!1},get_as_pair_array:function(){var b,d=[];for(b in c)c.hasOwnProperty(b)&&
d.push([b,c[b]]);return d},get_as_hash_node_dict:function(){var b,d={};for(b in c)c.hasOwnProperty(b)&&(d[b]=c[b]);return d},length:function(){return C.size(c)},add_node:function(c,d){return b(c,d)}}}(),Z=function(){function b(b,d){var e,f,g,n,p,l,q=[],t=[];if(!d)return t;if(!(null==b||"-1"===b)){e=Bc(b);e=c[e];if(!e)return t;l=e.search_objects;f=d.data;for(e=0,p=l.length;e<p;e++){var r=l[e];g=r.phrase;n={start:-1};n.phrase=g;n.text=null;if(0<g.limit())if(g=f.match(r.regex)){var v=g[0].indexOf(g[1]);
n.start=g.index+(-1!==v?v:0);n.text=f.substring(n.start,n.start+g[1].length);n.target_occurence=r.target_occurence}else n.start=-1;g=0;-1!=n.start&&n.text&&(g=1);g?(n.repl_regex=r.repl_regex,n.replacement=r.replacement,q.push(n)):n.start=-1}if(q&&q.length){q.sort(fc);p=q.length;f=[];for(e=0;e<p;e++){n=q[e];l={};r=!0;l.lower=n.start;l.upper=n.start+n.text.length;g=0;for(v=f.length;g<v;g++){var w=f[g];if(l.lower>=w.lower&&l.lower<=w.upper||l.upper<=w.upper&&l.upper>=w.lower||w.lower>=l.lower&&w.upper<=
l.upper){r=!1;break}}r&&(t.push(n),f.push(l))}q=f=null}t.sort(function(b,c){return b.start-c.start});return t}}var c,d,e=5,f={};return{store:function(b){var g,k,m,s,n,p,l,q,t,r,v;c=b.Nodes;d=b.country;e=Hc?0:b.Maxkeywords;null!=e&&(e=5);for(g in c)if(c.hasOwnProperty(g)){b=c[g];k=b.Phrases;s=[];for(p=0,l=k.length;p<l;p++){m=Jd(k[p]);t=m.action_type();r=Sc(Oa,t,q);q=0;if(n=ae(m))q=n.id(),f[q]=n,m.set_id(n.product_id());n=m.id();n=Ec(parseInt(n),t);v=n===m.id()?n:0;1E7<parseInt(n)&&6!==t&&(v=n-=1E7);
t=Rc(m,cb,n,q,v,r);s.push({phrase:m,repl_regex:t.repl_regex,replacement:t.repl_text,regex:t.search_regex,target_occurence:k[p].PhraseOccurrence})}s.sort(fc);b.search_objects=s}},find_matches:b,country:function(){return d},num_nodes:function(){return C.size(c)},maxkeywords:function(){return e},spanify_all:function(){var c,d,e,f,g,n=L.get_as_pair_array(),p,l=[];p={};for(d=0;d<n.length;d++)if(p=n[d],hash=p[0],c=p[1],e=b(hash,c),p={},e&&e.length){e=dc(e,c,hash);c=e[0];e=e[1];for(f=0,g=c.length;f<g;f++){var q=
c[f].match.phrase.text();p.hasOwnProperty(q)?p[q]++:p[q]=1;v(c[f],"occurence",p[q]);l.push(c[f])}for(f=0,g=e.length;f<g;f++)n.push([hash,e[f]])}return l},group_from_link:function(b){b=P(b,"group-id");return f[b]?f[b]:null}}}(),Jd=function(b){var c,d=null,e=null;c=b.Limit?b.Limit:5;return{group_id:function(){return d?d.id():0},dec_limit:function(){return c--},limit:function(){return c},action_type:function(){return b.ActionType},text:function(){return b.OriginalPhrase},url:function(){return b.Url},
multi:function(){return b.Mt?!0:!1},group_priority:function(){return d?d.group_priority():b.Priority},id:function(){return e?e:b.PhraseId},groups:function(){var c=b.Groups;return null!=c?c:[]},title:function(){return tit=b.Unlinked?"":b.ActionTitle?b.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(c){b.Title=b.Unlinked?"":c},occurence:function(){return b.PhraseOccurence},set_group:function(b){d=b},set_id:function(b){e=b}}},be=function(b,c){_phrase=c;return{id:function(){return b.GroupId},
group_priority:function(){return b.GroupPriority},products:function(){return b.Products},phrase:function(){return _phrase}}},Qd=function(b,c){function d(){return f.Id}var e=!1,f=b;return{id:d,adjusted_id:function(){var b=d(),e=c.phrase().action_type();1E7<b&&6!==e&&(b-=1E7);return b},title:function(){return f.Title},price:function(){return f.Price},vertica_id:function(){return parseInt(f.VerticalId)},url:function(){return f.Url},image:function(){return f.Image},merchant_name:function(){return f.MerchantName},
merchant_id:function(){return parseInt(f.MerchantId)},country_id:function(){return parseInt(f.CountryId)},ecpc:function(){return parseFloat(f.Ecpc)},is_first:function(){return e},set_first:function(){e=!0},group:function(){return c},country:function(){var b=Z.country();b||(b="US");return f.Country?f.Country.toUpperCase():b},action_type:function(){return c.phrase().action_type()}}},ae=function(b){var c,d,e,f;c=[];var g=b.groups(),j=null,k=b.multi(),m="$",s="The availability and pricing displayed are not guaranteed and are subject to change.",
n=null;if(g.length){for(e=0,f=g.length;e<f;e++)group=g[e],group_obj=be(group,b),c.push(group_obj);e=Pd(b,c);j=e[0];d=e[1];b.set_group(j);for(e=0,f=d.length;e<f;e++){c=d[e];switch(c.country()){case "GB":m="&pound;";break;case "DE":m="&euro;",u=String.fromCharCode(252),o=String.fromCharCode(246),a=String.fromCharCode(228),aa=String.fromCharCode(196),s="Die Verf"+u+"gbarkeit der Produkte und der ver"+o+"ffentlichte Preis werden nicht garantiert. Preis"+a+"nderungen und "+aa+"nderung der Verf"+u+"gbarkeit vorbehalt."}if(ga&&
c.merchant_id()===ga){n=c;k=!1;break}}}else return null;return{branded_product:function(){return n},is_multi:function(){return k},hover_title:function(){return s},currency:function(){return m},get_sorted_products:function(){return d},flyover_version:function(){var b=parseInt(Oa);if(n)return"04";k&&(b+=1);return 10>b?"0"+b:""+b},phrase:function(){return b},id:function(){return j.id()},product_id:function(){return d[0].id()}}},Ud=function(){return function(b,c){if(!b)return[[],[]];var d=b.data,e=[],
f,g,j;g=[];var k,m,s;j="3"+bb+"002";for(var n=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5})[^\[\]\s]*\b|$/ig,p;k=n.exec(d);)if(f=k[0],"link.phrase"!==f)if(k=k.index,0<Ba(f).length&&-1==f.indexOf("/.")&&-1==f.indexOf("..."))m=f,0!==f.indexOf("http")&&0!==f.indexOf("//")&&(m="msie"===w.browser&&6>=w.version?"http://"+f:"//"+f),p=pc(m),s=Jd({OriginalPhrase:""+f,Url:m,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(repl_obj=Rc(s,cb,0,0,0,j,"skimwords-unlinked"))&&g.push({start:k,
text:""+f,domain:p,repl_regex:repl_obj.repl_regex,replacement:repl_obj.repl_text,regex:repl_obj.search_regex,phrase:s,link:m}),e.push(p);else break;f=dc(g,b,c,"skimwords-unlinked");d=f[0];j=f[1];for(f=0,g=d.length;f<g;f++)Ra.push(d[f]);return[e,j]}}(),Pa=function(){var b=RegExp("{{([a-z0-9_][\\.a-z0-9_]*)}}","gi");return function(c,d){return c.replace(b,function(b,c){for(var g=c.split("."),j=g.length,k=d,m=0;m<j;m++)if(k=k[g[m]],m===j-1)return k})}}();g.skimwordsDataCallback=kb;g.instantDataCallback=
function(b){""==N&&b.guid&&(N=b.guid);g.skimlinks_runner&&(g.skimlinks_runner.skimwords=1);2!==b.nc&&(b.includes?L.traverse(b.includes,b.excludes):L.traverse(["body"],[]),1===b.nc?Dc(b):kb(b))};g.skimwordsReload=function(b){Ca=!0;yd();jb();T=!1;for(var c=F("head link[rel=stylesheet]"),d=0,e=c.length;d<e;d++){var f=c[d];f.href&&-1!==f.href.indexOf("skimlinks.")&&C.create(f).remove()}fb=!1;b||Uc();L.reset();Na=0;ob();Eb()};g.skimwordsUnlinked=function(b){var c,d,e,f={};if((c=b.merchant_domains)&&c.length){for(b=
0,e=c.length;b<e;b++)f[c[b]]=1;for(b=0,e=Ra.length;b<e;b++)c=Ra[b],d=c.match.domain,f[d]&&ec(c.node,c.match)}setTimeout(function(){for(var b=W("skimwords-unlinked"),c,d=0,e=b.length;d<e;d++)c=b[d],ac(c),mb&&mb(c)},10);try{Ga()}catch(g){}};Ad()})();
